### PR TITLE
Simplified script running

### PR DESCRIPTION
**Pull request by k06a**
Let's wait for the second one-liner simplification :)
http://unix.stackexchange.com/questions/306007/how-to-pass-argument-to-script-which-is-input-to-bash

### CODE REVIEW

**Comment by k06a** [comment]
Any plans to review?

**Comment by dominik-hadl** [comment]
@k06a Hey, sorry for the delay, I've actually tried this and forgot to reply 😄 

The issue with this is, that it doesn't work as soon as you have multiple Xcode versions installed. I actually had the same implementation in the beginning but then went with the another one.

Another thing is, that it is generally unsafe to pipe curl into bash as if the curl gets interrupted it will still pass whatever it loaded into bash, which in some cases could result in nasty issues :) Check out this [article](https://www.seancassidy.me/dont-pipe-to-your-shell.html).

If you, however, figure out a better solution that works and is safe, then please feel free to open a new pull request.

**Comment by k06a** [comment]
Your code does exactly the same it is not less secure, it's the same secure, but shorter :)

**Comment by dominik-hadl** [comment]
Well, I am not going to say my bash skills are so great, but I think it is as I am using the `&&` operator which relies on the previous command succeeding, which means returning exit code 0. 

So, if the curl for whatever reason fails, it won't continue.

And your version is shorter, but it also doesn't work with the way the updater script is written now. :)

**Pull request closed without merging**
